name: Build and Release Dynamic Toolbox

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v2.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List available Xcode versions
      run: ls /Applications/ | grep -E '^Xcode.*\.app$'
      
    - name: Select Xcode version
      run: |
        # Try to find the newest available Xcode
        if [ -d "/Applications/Xcode_16.app" ]; then
          sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
          echo "Using Xcode 16"
        elif [ -d "/Applications/Xcode_15.4.app" ]; then
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          echo "Using Xcode 15.4"
        else
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          echo "Using default Xcode"
        fi
        
    - name: Build Release
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Building version: $VERSION"
        
        # Show Xcode version for debugging
        xcodebuild -version
        
        # Clean any previous builds
        rm -rf build release
        mkdir -p build release
        
        # Build the app
        echo "Starting build..."
        xcodebuild -project DynamicIsland.xcodeproj \
                   -scheme DynamicIsland \
                   -configuration Release \
                   -archivePath "build/DynamicIsland.xcarchive" \
                   -destination "generic/platform=macOS" \
                   archive
        
        echo "Build completed, creating export options..."
        
        # Create export options
        cat > build/ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>mac-application</string>
            <key>destination</key>
            <string>export</string>
        </dict>
        </plist>
        EOF
        
        echo "Exporting app..."
        
        # Export the app
        xcodebuild -exportArchive \
                   -archivePath "build/DynamicIsland.xcarchive" \
                   -exportPath "build" \
                   -exportOptionsPlist "build/ExportOptions.plist"
        
        echo "Finding exported app..."
        
        # Find the exported app
        APP_PATH=$(find build -name "*.app" -type d | head -1)
        echo "Found app at: $APP_PATH"
        
        if [ -z "$APP_PATH" ]; then
            echo "Error: Could not find exported app"
            ls -la build/
            exit 1
        fi
        
        echo "Creating DMG..."
        
        # Create DMG
        DMG_NAME="Dynamic-Toolbox-v$VERSION"
        
        # Create temporary DMG directory
        mkdir -p build/dmg_temp
        
        # Copy app to DMG directory
        cp -R "$APP_PATH" build/dmg_temp/
        
        # Rename app for proper display in DMG
        if [ -d "build/dmg_temp/DynamicIsland.app" ]; then
            mv "build/dmg_temp/DynamicIsland.app" "build/dmg_temp/Dynamic Toolbox.app"
            echo "Renamed app to 'Dynamic Toolbox.app'"
        fi
        
        # Create Applications symlink
        ln -sf /Applications build/dmg_temp/Applications
        
        # Create DMG
        hdiutil create -volname "Dynamic Toolbox v$VERSION" \
                       -srcfolder build/dmg_temp \
                       -ov \
                       -format UDZO \
                       "release/$DMG_NAME.dmg"
        
        echo "DMG created successfully: release/$DMG_NAME.dmg"
        
        # Verify DMG was created
        if [ -f "release/$DMG_NAME.dmg" ]; then
            DMG_SIZE=$(du -h "release/$DMG_NAME.dmg" | cut -f1)
            echo "DMG size: $DMG_SIZE"
            ls -la release/
        else
            echo "Error: DMG was not created"
            exit 1
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Dynamic Toolbox ${{ github.ref_name }}"
        body: |
          🧰 **Dynamic Toolbox ${{ github.ref_name }}** is here!
          
          ## 🚀 What's New
          - Enhanced AI assistant with web search capabilities
          - Improved system monitoring with accurate RAM calculations
          - Beautiful chat history management
          - One-click copy for AI responses
          - Better file handling and smart conversation titles
          
          ## 📥 Installation
          1. Download `Dynamic-Toolbox-${{ github.ref_name }}.dmg`
          2. Open the DMG file
          3. Drag "Dynamic Toolbox" to your Applications folder
          4. Launch from Applications and enjoy!
          
          ## 📋 Requirements
          - macOS 15.1 (Sequoia) or later
          - Apple Silicon Mac recommended
          - ~50MB storage space
          - Internet connection (optional, for weather/currency/web search)
          
          ## 🤖 AI Features (Optional)
          - Install [Ollama](https://ollama.ai) for local AI capabilities
          - Recommended model: `llama3.2:3b` (~2GB)
          - Run: `ollama pull llama3.2:3b`
          
          ---
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v1.0.0...${{ github.ref_name }}
        files: |
          release/*.dmg
          README.md
          Distribution/Installation-Guide.txt
          Distribution/Release-Notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 